# Generated by Django 3.1.5 on 2021-01-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('img', models.ImageField(upload_to='')),
                ('contact', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
