# Generated by Django 3.1.5 on 2021-01-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='img',
            field=models.ImageField(upload_to='images/<built-in method date of datetime.datetime object at 0x000001CFD0615090>'),
        ),
        migrations.AlterField(
            model_name='item',
            name='location',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
