# Generated by Django 3.1.5 on 2021-02-09 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20210205_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='date_crawled',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='item',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.tag'),
        ),
        migrations.AlterField(
            model_name='item',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/2021/02/09'),
        ),
    ]
