# Generated by Django 3.1.5 on 2021-02-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20210209_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='visits',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/2021/02/13'),
        ),
    ]
