# Generated by Django 3.1.5 on 2021-03-07 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_auto_20210307_1858'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
