# Generated by Django 3.1.5 on 2021-03-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='visits',
            field=models.IntegerField(default=0),
        ),
    ]
