# Generated by Django 3.1.5 on 2021-03-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_auto_20210309_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/2021/03/09'),
        ),
    ]
