# Generated by Django 3.1.5 on 2021-03-21 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_auto_20210321_1314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='name',
            new_name='bio',
        ),
    ]
