# Generated by Django 3.1.5 on 2021-04-27 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_auto_20210416_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/2021/04/27'),
        ),
        migrations.AlterField(
            model_name='store',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/2021/04/27'),
        ),
    ]
