# Generated by Django 3.1.5 on 2021-06-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_item_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='height_field',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='width_field',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='img',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='images/2021/06/02', width_field='width_field'),
        ),
        migrations.AlterField(
            model_name='store',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/2021/06/02'),
        ),
    ]
