# Generated by Django 3.1.5 on 2021-06-03 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_auto_20210602_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='item',
            name='width_field',
        ),
        migrations.AlterField(
            model_name='item',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/2021/06/03'),
        ),
        migrations.AlterField(
            model_name='store',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/2021/06/03'),
        ),
    ]
