# Generated by Django 3.1.5 on 2021-06-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_auto_20210603_2352'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=50)),
                ('type', models.CharField(blank=True, choices=[('Whatsapp', 'Whatsapp'), ('Normal Calls', 'Normal Calls')], max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='date_crawled',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='img',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='images/2021/06/19', width_field='width_field'),
        ),
        migrations.AlterField(
            model_name='store',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/2021/06/19'),
        ),
    ]
