# Generated by Django 3.1.5 on 2021-06-19 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_auto_20210619_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcontact',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.item'),
        ),
        migrations.AlterField(
            model_name='itemcontact',
            name='type',
            field=models.CharField(blank=True, choices=[('whatsapp', 'whatsapp'), ('normal calls', 'normal calls')], max_length=50),
        ),
    ]
