# Generated by Django 3.1.5 on 2021-06-19 20:47

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_auto_20210619_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='img',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=myapp.models.Item.image_directory_path, width_field='width_field'),
        ),
    ]
