# Generated by Django 3.1.5 on 2021-06-19 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_auto_20210619_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/2021/06/20'),
        ),
    ]
